# Generated by Django 4.2.30 on 2026-06-26 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kamsa_auto', '0002_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='inclut_chauffeur',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reservation',
            name='prix_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
