# Generated by Django 4.2.30 on 2026-06-26 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kamsa_auto', '0003_reservation_inclut_chauffeur_reservation_prix_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicule',
            name='categorie',
            field=models.CharField(choices=[('economique', 'Économique'), ('suv', 'SUV et 4x4'), ('utilitaire', 'Utilitaires'), ('luxe', 'Luxe')], default='economique', max_length=20),
        ),
    ]
