# Generated by Django 4.2.30 on 2026-07-02 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kamsa_auto', '0004_vehicule_categorie'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='statut_paiement',
            field=models.CharField(choices=[('unpaid', 'Non payé'), ('paid', 'Payé'), ('failed', 'Échoué')], default='unpaid', max_length=10),
        ),
        migrations.AddField(
            model_name='reservation',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
