# Generated by Django 4.2.30 on 2026-07-09 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kamsa_auto', '0005_reservation_statut_paiement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='permis_conduire',
            field=models.FileField(help_text='Fichier du permis de conduire (PDF, JPG, PNG)', null=True, upload_to='permis/'),
        ),
    ]
