# Generated by Django 4.2.30 on 2026-07-09 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kamsa_auto', '0006_client_permis_conduire'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContacteMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_complet', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('sujet', models.CharField(choices=[('renseignements', 'Renseignements généraux'), ('partenariat', "Partenariat d'entreprise"), ('assistance', 'Assistance routière'), ('autre', 'Autre')], default='renseignements', max_length=50)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
